apiVersion: v1
kind: Service
metadata:
  name: dev-service
  namespace: dev-namespace
spec:
  selector:
    app: dev-deployment
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32100
  type: NodePort
