apiVersion: v1
kind: Service
metadata:
  name: prod-service
  namespace: prod-namespace
spec:
  selector:
    app: prod-deployment
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32000
  type: NodePort
